routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('triplogin', 'Auth\TripLoginController@triplogin')->name('auth.trip_login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

$this->get('trip_login', 'Auth\TripLoginController@showTripLoginForm')->name('auth.trip_login');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

$this->get('invitation/{invitation_token}', 'Auth\RegisterController@processInvitation')->name('auth.invitation');



    Route::group(['prefix' => 'trip', 'as' => 'trip.'], function () {
        Route::get('home', 'TripController@index');
        Route::get('tours', 'TripController@tourListing');
        Route::match(['get','post'],'feedback/{id}', 'TripController@feedback');
        Route::match(['get','post'],'feedback/{id}/{notid}', 'TripController@feedback');
        Route::get('survey', 'TripController@surveyListing');
        
    });
    Route::group(['middleware' => ['auth', 'check_invitation'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::get('surveys', 'Admin\QuestionnaireController@surveys');
    Route::get('survey', 'Admin\QuestionnaireController@surveyListing');
    Route::get('tours', 'Admin\ToursController@tourListing');
    
    Route::match(['get','post'],'createsurvey', 'Admin\QuestionnaireController@createSurvey');
    
    Route::resource('questionnaires', 'Admin\QuestionnaireController');
    Route::post('questionnaires_mass_destroy', ['uses' => 'Admin\QuestionnaireController@massDestroy', 'as' => 'questionnaires.mass_destroy']);
	Route::get('getquesans', 'Admin\QuestionnaireController@getAnswers');
    Route::match(['get','post'],'survey/edit/{id}', 'Admin\QuestionnaireController@surveyEdit');
    Route::match(['get','post'],'survey/view/{id}', 'Admin\QuestionnaireController@surveyView');
	
	Route::match(['get','post'],'questionnaires/create/{id}', 'Admin\QuestionnaireController@add');
	Route::match(['get','post'],'questionnaires/edit/{id}', 'Admin\QuestionnaireController@edit');
    Route::get('deletequestionnaire/{id}', 'Admin\QuestionnaireController@delete');
    Route::get('deletesurvey/{id}', 'Admin\QuestionnaireController@deleteSurvey');
    
    Route::match(['get','post'],'profile', 'Admin\UsersController@profile');
    Route::match(['get','post'],'feedback/{id}', 'Admin\QuestionnaireController@feedback');
    Route::match(['get','post'],'feedback/{id}/{notid}', 'Admin\QuestionnaireController@feedback');
    
    
    
	//Route::match(['get','post'],'surveys', 'Admin\QuestionnaireController@questionnaires');
    
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('properties', 'Admin\PropertiesController');
    Route::post('properties_mass_destroy', ['uses' => 'Admin\PropertiesController@massDestroy', 'as' => 'properties.mass_destroy']);
    Route::post('properties_restore/{id}', ['uses' => 'Admin\PropertiesController@restore', 'as' => 'properties.restore']);
    Route::delete('properties_perma_del/{id}', ['uses' => 'Admin\PropertiesController@perma_del', 'as' => 'properties.perma_del']);
    Route::resource('documents', 'Admin\DocumentsController');
    Route::post('documents_mass_destroy', ['uses' => 'Admin\DocumentsController@massDestroy', 'as' => 'documents.mass_destroy']);
    Route::post('documents_restore/{id}', ['uses' => 'Admin\DocumentsController@restore', 'as' => 'documents.restore']);
    Route::delete('documents_perma_del/{id}', ['uses' => 'Admin\DocumentsController@perma_del', 'as' => 'documents.perma_del']);
    Route::resource('notes', 'Admin\NotesController');
    Route::post('notes_mass_destroy', ['uses' => 'Admin\NotesController@massDestroy', 'as' => 'notes.mass_destroy']);
    Route::post('notes_restore/{id}', ['uses' => 'Admin\NotesController@restore', 'as' => 'notes.restore']);
    Route::delete('notes_perma_del/{id}', ['uses' => 'Admin\NotesController@perma_del', 'as' => 'notes.perma_del']);

    Route::model('messenger', 'App\MessengerTopic');
    Route::get('messenger/inbox', 'Admin\MessengerController@inbox')->name('messenger.inbox');
    Route::get('messenger/outbox', 'Admin\MessengerController@outbox')->name('messenger.outbox');
    Route::resource('messenger', 'Admin\MessengerController');

    Route::resource('tenants', 'Admin\TenantsController');
 
});

app/Role.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Role
 *
 * @package App
 * @property string $title
*/
class Role extends Model
{
    protected $fillable = ['title'];
    
    
    
    public function permission()
    {
        return $this->belongsToMany(Permission::class, 'permission_role');
    }

    
    
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreRolesRequest;
use App\Http\Requests\Admin\UpdateRolesRequest;

class RolesController extends Controller
{
    /**
     * Display a listing of Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('role_access')) {
            return abort(401);
        }

        $roles = Role::all();

        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating new Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('role_create')) {
            return abort(401);
        }

        $permissions = \App\Permission::get()->pluck('title', 'id');

        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created Role in storage.
     *
     * @param  \App\Http\Requests\StoreRolesRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRolesRequest $request)
    {
        if (! Gate::allows('role_create')) {
            return abort(401);
        }

        $role = Role::create($request->all());
        $role->permission()->sync(array_filter((array)$request->input('permission')));

        return redirect()->route('admin.roles.index');
    }


    /**
     * Show the form for editing Role.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('role_edit')) {
            return abort(401);
        }

        $permissions = \App\Permission::get()->pluck('title', 'id');
        $role        = Role::findOrFail($id);

        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update Role in storage.
     *
     * @param  \App\Http\Requests\UpdateRolesRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRolesRequest $request, $id)
    {
        if (! Gate::allows('role_edit')) {
            return abort(401);
        }

        $role = Role::findOrFail($id);
        $role->update($request->all());
        $role->permission()->sync(array_filter((array)$request->input('permission')));

        return redirect()->route('admin.roles.index');
    }


    /**
     * Display Role.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('role_view')) {
            return abort(401);
        }

        $permissions = \App\Permission::get()->pluck('title', 'id');
        $users       = \App\User::whereHas('role',
            function ($query) use ($id) {
                $query->where('id', $id);
            })->get();
        $role        = Role::findOrFail($id);

        return view('admin.roles.show', compact('role', 'users'));
    }


    /**
     * Remove Role from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('role_delete')) {
            return abort(401);
        }

        $role = Role::findOrFail($id);
        $role->delete();

        return redirect()->route('admin.roles.index');
    }

    /**
     * Delete all selected Role at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('role_delete')) {
            return abort(401);
        }

        if ($request->input('ids')) {
            $entries = Role::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/admin/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="page-body">
<div class="row">
    <div class="col-sm-12">
        <!-- Basic Form Inputs card start -->
        <div class="card">
            <div class="card-header">
                <h5>Create Role</h5>
                </div>
                <div class="card-block">
    {!! Form::open(['method' => 'POST', 'route' => ['admin.roles.store']]) !!}

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label"> {!! Form::label('title',
                            trans('global.roles.fields.title').'*', ['class' => 'control-label'])
                            !!}</label>
                        <div class="col-sm-10">
                            {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => '',
                            'required' =>
                            '']) !!}
                        </div>



                        <p class="help-block"></p>
                        @if($errors->has('title'))
                        <p class="help-block">
                            {{ $errors->first('title') }}
                        </p>
                        @endif
                    </div>

                    <div class="form-group row">

                        <label class="col-sm-2 col-form-label"> {!! Form::label('permission',
                            trans('global.roles.fields.permission').'*', ['class' =>
                            'control-label']) !!}</label>
                        <div class="col-sm-10">
                            {!! Form::select('permission[]', $permissions, old('permission'), ['class' => 'form-control
                            select2', 'multiple' => 'multiple', 'required' => '']) !!}
                        </div>

                        <p class="help-block"></p>
                        @if($errors->has('permission'))
                        <p class="help-block">
                            {{ $errors->first('permission') }}
                        </p>
                        @endif
                    </div>
    {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
    </div>
    </div>
</div>
</div>
</div>
@stop

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="page-body">
<div class="row">
    <div class="col-sm-12">
        <!-- Basic Form Inputs card start -->
        <div class="card">
            <div class="card-header">
                <h5>Edit Role</h5>
                </div>
                <div class="card-block">
            {!! Form::model($role, ['method' => 'PUT', 'route' => ['admin.roles.update', $role->id]]) !!}

                            <div class="form-group row">

                                <label class="col-sm-2 col-form-label"> {!! Form::label('title',
                                    trans('global.roles.fields.title').'*', ['class' => 'control-label'])
                                    !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' =>
                                    '',
                                    'required' =>
                                    '']) !!}
                                </div>



                                <p class="help-block"></p>
                                @if($errors->has('title'))
                                <p class="help-block">
                                    {{ $errors->first('title') }}
                                </p>
                                @endif
                            </div>

                            <div class="form-group row">

                                <label class="col-sm-2 col-form-label"> {!! Form::label('permission',
                                    trans('global.roles.fields.permission').'*', ['class' =>
                                    'control-label'])
                                    !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::select('permission[]', $permissions, old('permission') ? old('permission')
                                    :
                                    $role->permission->pluck('id')->toArray(), ['class' => 'form-control select2',
                                    'multiple' =>
                                    'multiple',
                                    'required' => '']) !!}
                                </div>



                                <p class="help-block"></p>
                                @if($errors->has('permission'))
                                <p class="help-block">
                                    {{ $errors->first('permission') }}
                                </p>
                                @endif
                            </div>
   

            {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
            </div>
    </div>
</div>
</div>
</div>
@stop

resources/views/admin/roles/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
<div class="page-body">
    <!-- Basic table card start -->
    @can('role_create')
    <p>
        <a class="btn btn-success" href="{{ route('admin.roles.create') }}" class="">Create</a>
        
    </p>
    @endcan
@if (Session::has('success'))
<div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>{{Session::get('success') }}</strong>
</div>
@endif
@if (Session::has('error'))
<div class="alert alert-danger alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>{{Session::get('error') }}</strong>
</div>
@endif
<div class="card">
<!-- Right side column. Contains the navbar and content of the page -->
<div class="card-header">
    <h5>Role Listing</h5>
</div>
<div class="card-block table-border-style">
         <div class="table-responsive">
            <table class="table table-bordered table-striped {{ count($roles) > 0 ? 'datatable' : '' }}">
                <thead>
                    <tr>
                       

                        <th>@lang('global.roles.fields.title')</th>
                        <!--<th>@lang('global.roles.fields.permission')</th>-->
                                                <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($roles) > 0)
                        @foreach ($roles as $role)
                            <tr data-entry-id="{{ $role->id }}">
                              

                                <td field-key='title'>{{ $role->title }}</td>
                               <!-- <td field-key='permission'>
                                    @foreach ($role->permission as $singlePermission)
                                        <span class="label label-info label-many">{{ $singlePermission->title }}</span>
                                    @endforeach
                                </td>-->
                                                                <td class="action">
                                    @can('role_view')
                                    <a href="{{ route('admin.roles.show',[$role->id]) }}" class="bob_no_btn"><i class="ti-view-list"></i></a>
                                    @endcan
                                    @can('role_edit')
                                    <a href="{{ route('admin.roles.edit',[$role->id]) }}" class="bob_no_btn"><i class="ti-pencil"></i></a>
                                    @endcan
                                    @can('role_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.roles.destroy', $role->id])) !!}
                                    {!! Form::button('<i class="ti-trash"></i>', array('type' => 'submit','class' => 'bob_no_btn')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="7">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
            </div>
        </div>
    </div>
</div>
@stop

@section('javascript') 
    <script>
        @can('role_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.roles.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.app')

@section('content')
<h3 class="page-title">@lang('global.roles.title')</h3>

  <div class="page-body">
    <div class="row">
        <div class="col-sm-12">

    <div class="panel-body table-responsive">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>@lang('global.roles.fields.title')</th>
                        <td field-key='title'>{{ $role->title }}</td>
                    </tr>
                     <!--<tr>
                        <th>@lang('global.roles.fields.permission')</th>
                       <td field-key='permission'>
                            @foreach ($role->permission as $singlePermission)
                            <span class="label label-info label-many">{{ $singlePermission->title }}</span>
                            @endforeach
                        </td>
                    </tr> -->
                </table>
            </div>
        </div><!-- Nav tabs -->
        

        <!-- Tab panes -->
		<div class="card" style="width:100%">
			<div class="col-sm-12">
			<div class="panel-heading">
			  
			</div>
        <div class="tab-content">

            <div role="tabpanel" class="tab-pane active" id="users">
                <table class="table table-bordered table-striped {{ count($users) > 0 ? 'datatable' : '' }}">
                    <thead>
                        <tr>
                            <th>@lang('global.users.fields.name')</th>
                            <th>@lang('global.users.fields.email')</th>
                            <th>@lang('global.users.fields.role')</th>
                            <th>&nbsp;</th>

                        </tr>
                    </thead>

                    <tbody>
                        @if (count($users) > 0)
                        @foreach ($users as $user)
                        <tr data-entry-id="{{ $user->id }}">
                            <td field-key='name'>{{ $user->name }}</td>
                            <td field-key='email'>{{ $user->email }}</td>
                            <td field-key='role'>
                                @foreach ($user->role as $singleRole)
                                <span class="label label-info label-many">{{ $singleRole->title }}</span>
                                @endforeach
                            </td>
                            <td>
                                @can('view')
                                <a href="{{ route('users.show',[$user->id]) }}"
                                    class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                @endcan
                                @can('edit')
                                <a href="{{ route('users.edit',[$user->id]) }}"
                                    class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                @endcan
                                @can('delete')
                                {!! Form::open(array(
                                'style' => 'display: inline-block;',
                                'method' => 'DELETE',
                                'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                'route' => ['users.destroy', $user->id])) !!}
                                {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger'))
                                !!}
                                {!! Form::close() !!}
                                @endcan
                            </td>

                        </tr>
                        @endforeach
                        @else
                        <tr>
                            <td colspan="10">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>

        <p>&nbsp;</p>

        <a href="{{ route('admin.roles.index') }}" class="btn btn-secondary">@lang('global.app_back_to_list')</a>
        <p>&nbsp;</p>
    </div>
</div>
    </div>
</div>
    </div>
</div>
@stop