routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('triplogin', 'Auth\TripLoginController@triplogin')->name('auth.trip_login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

$this->get('trip_login', 'Auth\TripLoginController@showTripLoginForm')->name('auth.trip_login');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

$this->get('invitation/{invitation_token}', 'Auth\RegisterController@processInvitation')->name('auth.invitation');



    Route::group(['prefix' => 'trip', 'as' => 'trip.'], function () {
        Route::get('home', 'TripController@index');
        Route::get('tours', 'TripController@tourListing');
        Route::match(['get','post'],'feedback/{id}', 'TripController@feedback');
        Route::match(['get','post'],'feedback/{id}/{notid}', 'TripController@feedback');
        Route::get('survey', 'TripController@surveyListing');
        
    });
    Route::group(['middleware' => ['auth', 'check_invitation'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::get('surveys', 'Admin\QuestionnaireController@surveys');
    Route::get('survey', 'Admin\QuestionnaireController@surveyListing');
    Route::get('tours', 'Admin\ToursController@tourListing');
    
    Route::match(['get','post'],'createsurvey', 'Admin\QuestionnaireController@createSurvey');
    
    Route::resource('questionnaires', 'Admin\QuestionnaireController');
    Route::post('questionnaires_mass_destroy', ['uses' => 'Admin\QuestionnaireController@massDestroy', 'as' => 'questionnaires.mass_destroy']);
	Route::get('getquesans', 'Admin\QuestionnaireController@getAnswers');
    Route::match(['get','post'],'survey/edit/{id}', 'Admin\QuestionnaireController@surveyEdit');
    Route::match(['get','post'],'survey/view/{id}', 'Admin\QuestionnaireController@surveyView');
	
	Route::match(['get','post'],'questionnaires/create/{id}', 'Admin\QuestionnaireController@add');
	Route::match(['get','post'],'questionnaires/edit/{id}', 'Admin\QuestionnaireController@edit');
    Route::get('deletequestionnaire/{id}', 'Admin\QuestionnaireController@delete');
    Route::get('deletesurvey/{id}', 'Admin\QuestionnaireController@deleteSurvey');
    
    Route::match(['get','post'],'profile', 'Admin\UsersController@profile');
    Route::match(['get','post'],'feedback/{id}', 'Admin\QuestionnaireController@feedback');
    Route::match(['get','post'],'feedback/{id}/{notid}', 'Admin\QuestionnaireController@feedback');
    
    
    
	//Route::match(['get','post'],'surveys', 'Admin\QuestionnaireController@questionnaires');
    
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('properties', 'Admin\PropertiesController');
    Route::post('properties_mass_destroy', ['uses' => 'Admin\PropertiesController@massDestroy', 'as' => 'properties.mass_destroy']);
    Route::post('properties_restore/{id}', ['uses' => 'Admin\PropertiesController@restore', 'as' => 'properties.restore']);
    Route::delete('properties_perma_del/{id}', ['uses' => 'Admin\PropertiesController@perma_del', 'as' => 'properties.perma_del']);
    Route::resource('documents', 'Admin\DocumentsController');
    Route::post('documents_mass_destroy', ['uses' => 'Admin\DocumentsController@massDestroy', 'as' => 'documents.mass_destroy']);
    Route::post('documents_restore/{id}', ['uses' => 'Admin\DocumentsController@restore', 'as' => 'documents.restore']);
    Route::delete('documents_perma_del/{id}', ['uses' => 'Admin\DocumentsController@perma_del', 'as' => 'documents.perma_del']);
    Route::resource('notes', 'Admin\NotesController');
    Route::post('notes_mass_destroy', ['uses' => 'Admin\NotesController@massDestroy', 'as' => 'notes.mass_destroy']);
    Route::post('notes_restore/{id}', ['uses' => 'Admin\NotesController@restore', 'as' => 'notes.restore']);
    Route::delete('notes_perma_del/{id}', ['uses' => 'Admin\NotesController@perma_del', 'as' => 'notes.perma_del']);

    Route::model('messenger', 'App\MessengerTopic');
    Route::get('messenger/inbox', 'Admin\MessengerController@inbox')->name('messenger.inbox');
    Route::get('messenger/outbox', 'Admin\MessengerController@outbox')->name('messenger.outbox');
    Route::resource('messenger', 'Admin\MessengerController');

    Route::resource('tenants', 'Admin\TenantsController');
 
});

app/Http/Controllers/Admin/MessengerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreMessageRequest;
use App\Http\Requests\UpdateMessageRequest;
use App\Property;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;
use App\MessengerTopic;
use App\Http\Controllers\Controller;

class MessengerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $topics = Auth::user()->topics()->with('receiver', 'sender')->orderBy('sent_at', 'desc')->get();
        $title  = 'Messages';

        return view('admin.messenger.index', compact('topics', 'title'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = [];
        if (! auth()->user()->property_id) {
            $users = User::whereIn('property_id',
                Property::where('user_id', auth()->user()->id)->pluck('id'))->pluck('name', 'id');
        } else {
            $users = User::where('id', auth()->user()->property->user_id)->pluck('name', 'id');
        }

        return view('admin.messenger.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreMessageRequest|Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreMessageRequest $request)
    {
        $sender = Auth::user()->id;

        MessengerTopic::create([
            'subject'     => $request->input('subject'),
            'sender_id'   => $sender,
            'receiver_id' => $request->input('receiver'),
            'sent_at'     => Carbon::now(),
        ])->read()
            ->messages()->create([
                'sender_id' => $sender,
                'content'   => $request->input('content'),
            ]);

        return redirect()->route('admin.messenger.index');
    }

    /**
     * Display the specified resource.
     *
     * @param MessengerTopic $topic
     * @return \Illuminate\Http\Response
     * @internal param MessengerTopic $topic
     * @internal param int $id
     */
    public function show(MessengerTopic $topic)
    {

        $user = Auth::user();
        if ($topic->receiver->id != $user->id && $topic->sender->id != $user->id) {
            return abort(401);
        }

        $topic->load('receiver', 'sender', 'messages');
        $unreadMessages = [];
        foreach ($topic->messages as $message) {
            if ($message->unread($topic)) {
                $unreadMessages[] = $message->id;
            }
        }
        $topic->read();

        return view('admin.messenger.show', compact('topic', 'unreadMessages'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param MessengerTopic $topic
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function edit(MessengerTopic $topic)
    {
        $user = Auth::user();
        if ($topic->receiver->id != $user->id && $topic->sender->id != $user->id) {
            return abort(401);
        }
        $topic->load('receiver', 'sender');
        $user = $topic->otherPerson()->name;

        return view('admin.messenger.reply', compact('topic', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateMessageRequest|Request $request
     * @param MessengerTopic $topic
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function update(UpdateMessageRequest $request, MessengerTopic $topic)
    {


        $user = Auth::user();
        if ($topic->receiver->id != $user->id && $topic->sender->id != $user->id) {
            return abort(401);
        }

        $topic->sent_at = Carbon::now();
        $topic->save();
        $topic->read();
        $topic->messages()->create([
            'sender_id' => Auth::user()->id,
            'content'   => $request->input('content'),
        ]);

        return redirect()->route('admin.messenger.show', $topic->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param MessengerTopic $topic
     * @return \Illuminate\Http\Response
     * @throws \Exception
     * @internal param int $id
     */
    public function destroy(MessengerTopic $topic)
    {
        $user = Auth::user();
        if ($topic->receiver->id != $user->id && $topic->sender->id != $user->id) {
            return abort(401);
        }

        $topic->delete();

        return redirect()->route('admin.messenger.index');
    }

    public function inbox()
    {
        $topics = Auth::user()->inbox()->with('receiver', 'sender')->orderBy('sent_at', 'desc')->get();
        $title  = 'Inbox';

        return view('admin.messenger.index', compact('topics', 'title'));
    }

    public function outbox()
    {
        $topics = Auth::user()->outbox()->with('receiver', 'sender')->orderBy('sent_at', 'desc')->get();
        $title  = 'Outbox';

        return view('admin.messenger.index', compact('topics', 'title'));
    }
}

resources/views/admin/messenger/create.blade.php
@extends('admin.messenger.template')

@section('title', 'New message')

@section('messenger-content')

    <div class="row">
        <div class="col-md-12">
            {!! Form::open(['route' => ['admin.messenger.store'], 'method' => 'POST', 'novalidate', 'class' => 'stepperForm validate']) !!}

            @include('admin.messenger.form-partials.fields')

            {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </div>
    </div>

@stop

resources/views/admin/messenger/index.blade.php
@extends('admin.messenger.template')

@section('title', $title)

@section('messenger-content')
    <div class="row">
        <div class="col-md-12">
            <div class="list-group">
                @forelse($topics as $topic)
                    <div class="row list-group-item">
                        <div class="col-xs-4 col-md-4">
                            <a href="{{ route('admin.messenger.show', [$topic->id]) }}" class="{{$topic->unread()?'unread':false}}">
                                {{ $topic->otherPerson()->name }}
                            </a>
                        </div>
                        <div class="col-xs-5 col-md-5">
                            <a href="{{ route('admin.messenger.show', [$topic->id]) }}" class="{{$topic->unread()?'unread':false}}">
                                {{ $topic->subject }}
                            </a>
                        </div>
                        <div class="col-xs-2 text-right">{{ $topic->sent_at->diffForHumans() }}</div>
                        <div class="col-xs-1 text-center">
                            {!! Form::open(array(
                                    'style' => 'display: inline-block;',
                                    'method' => 'DELETE',
                                    'onsubmit' => "return confirm('Are you sure?');",
                                    'route' => ['admin.messenger.destroy', $topic->id])) !!}
                            {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                            {!! Form::close() !!}
                        </div>
                    </div>
                @empty
                    <div class="row list-group-item">
                        You have no messages.
                    </div>
                @endforelse
            </div>
        </div>
    </div>

    <style>
        .messenger-table tr:first-child td {
            border-top: 0 !important;
        }
        .unread {
            font-weight: bold;
            color:black;
        }
    </style>

@endsection

resources/views/admin/messenger/reply.blade.php
@extends('admin.messenger.template')

@section('title', 'New message')

@section('messenger-content')

    <div class="row">
        <div class="col-md-12">
            {{--{!! Form::open(['route' => ['admin.messenger.save'], 'method' => 'POST', 'novalidate', 'class' => 'stepperForm validate']) !!}--}}
            {!! Form::model($topic, ['method' => 'PUT', 'route' => ['admin.messenger.update', $topic->id]]) !!}

            @include('admin.messenger.form-partials.fields')

            {!! Form::submit('Reply', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </div>
    </div>

@stop

resources/views/admin/messenger/show.blade.php
@extends('admin.messenger.template')

@section('title', $topic->subject)

@section('messenger-content')

    <div class="row">
        <a href="{{ route('admin.messenger.edit', [$topic->id]) }}" class="btn btn-primary">Reply</a>

        <div class="col-md-12">
            <div class="list-group" style="margin-top:8px;">
                @foreach($topic->messages as $message)
                    <div class="row list-group-item">
                        <div class="row">
                            <div class="col col-xs-10 {{ (in_array($message->id, $unreadMessages)?"unread":false) }}">
                                {{ $message->sender->name }}
                            </div>
                            <div class="col col-xs-2">
                                {{  $message->sent_at->diffForHumans()/*format('d F Y h:i')*/ }}
                            </div>
                        </div>
                        <div>
                        </div>
                        <div class="row" style="padding-left:15px;">
                            <div class="col col-xs-12">
                                {{ $message->content }}
                            </div>
                        </div>
                    </div>

                @endforeach
            </div>

        </div>
    </div>

    <style>
        .messenger-table tr:first-child td {
            border-top: 0 !important;
        }

        .unread {
            font-weight: bold;
        }

        .list-group-item {
            border-top: 0;
            border-bottom: 0;
        }

        .list-group-item:first-child {
            border-top: 1px solid #ddd;
        }

        .list-group-item:last-child {
            border-bottom: 1px solid #ddd;
        }

        .list-group-item:hover {
            background-color: #eee;
        }
    </style>

@endsection

resources/views/admin/messenger/template.blade.php
@extends('layouts.app')

@section('content')

    <h2 style="margin-top:0px;">@yield('title')</h2>

    <div class="row" style="margin-top:15px;">

        {{--Sidebar--}}
        <div class="col-xs-3">
            <a href="{{ route('admin.messenger.create') }}" class="btn btn-primary btn-group-justified">New message</a>

            <div class="list-group" style="margin-top:8px;">
                <a href="{{ route('admin.messenger.index') }}" class="list-group-item">All Messages</a>
                @php($unread = App\MessengerTopic::unreadInboxCount())
                <a href="{{ route('admin.messenger.inbox') }}" class="list-group-item {{ ($unread > 0 ? 'unread' : '') }}">
                    Inbox
                    {{ ($unread > 0 ? '('.$unread.')' : '') }}
                </a>
                <a href="{{ route('admin.messenger.outbox') }}" class="list-group-item">Outbox</a>
            </div>
        </div>


        {{--Main content--}}
        <div class="col-xs-9">
            @yield('messenger-content')
        </div>
    </div>

@stop