routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('triplogin', 'Auth\TripLoginController@triplogin')->name('auth.trip_login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

$this->get('trip_login', 'Auth\TripLoginController@showTripLoginForm')->name('auth.trip_login');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

$this->get('invitation/{invitation_token}', 'Auth\RegisterController@processInvitation')->name('auth.invitation');



    Route::group(['prefix' => 'trip', 'as' => 'trip.'], function () {
        Route::get('home', 'TripController@index');
        Route::get('tours', 'TripController@tourListing');
        Route::match(['get','post'],'feedback/{id}', 'TripController@feedback');
        Route::match(['get','post'],'feedback/{id}/{notid}', 'TripController@feedback');
        Route::get('survey', 'TripController@surveyListing');
        
    });
    Route::group(['middleware' => ['auth', 'check_invitation'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::get('surveys', 'Admin\QuestionnaireController@surveys');
    Route::get('survey', 'Admin\QuestionnaireController@surveyListing');
    Route::get('tours', 'Admin\ToursController@tourListing');
    
    Route::match(['get','post'],'createsurvey', 'Admin\QuestionnaireController@createSurvey');
    
    Route::resource('questionnaires', 'Admin\QuestionnaireController');
    Route::post('questionnaires_mass_destroy', ['uses' => 'Admin\QuestionnaireController@massDestroy', 'as' => 'questionnaires.mass_destroy']);
	Route::get('getquesans', 'Admin\QuestionnaireController@getAnswers');
    Route::match(['get','post'],'survey/edit/{id}', 'Admin\QuestionnaireController@surveyEdit');
    Route::match(['get','post'],'survey/view/{id}', 'Admin\QuestionnaireController@surveyView');
	
	Route::match(['get','post'],'questionnaires/create/{id}', 'Admin\QuestionnaireController@add');
	Route::match(['get','post'],'questionnaires/edit/{id}', 'Admin\QuestionnaireController@edit');
    Route::get('deletequestionnaire/{id}', 'Admin\QuestionnaireController@delete');
    Route::get('deletesurvey/{id}', 'Admin\QuestionnaireController@deleteSurvey');
    
    Route::match(['get','post'],'profile', 'Admin\UsersController@profile');
    Route::match(['get','post'],'feedback/{id}', 'Admin\QuestionnaireController@feedback');
    Route::match(['get','post'],'feedback/{id}/{notid}', 'Admin\QuestionnaireController@feedback');
    
    
    
	//Route::match(['get','post'],'surveys', 'Admin\QuestionnaireController@questionnaires');
    
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('properties', 'Admin\PropertiesController');
    Route::post('properties_mass_destroy', ['uses' => 'Admin\PropertiesController@massDestroy', 'as' => 'properties.mass_destroy']);
    Route::post('properties_restore/{id}', ['uses' => 'Admin\PropertiesController@restore', 'as' => 'properties.restore']);
    Route::delete('properties_perma_del/{id}', ['uses' => 'Admin\PropertiesController@perma_del', 'as' => 'properties.perma_del']);
    Route::resource('documents', 'Admin\DocumentsController');
    Route::post('documents_mass_destroy', ['uses' => 'Admin\DocumentsController@massDestroy', 'as' => 'documents.mass_destroy']);
    Route::post('documents_restore/{id}', ['uses' => 'Admin\DocumentsController@restore', 'as' => 'documents.restore']);
    Route::delete('documents_perma_del/{id}', ['uses' => 'Admin\DocumentsController@perma_del', 'as' => 'documents.perma_del']);
    Route::resource('notes', 'Admin\NotesController');
    Route::post('notes_mass_destroy', ['uses' => 'Admin\NotesController@massDestroy', 'as' => 'notes.mass_destroy']);
    Route::post('notes_restore/{id}', ['uses' => 'Admin\NotesController@restore', 'as' => 'notes.restore']);
    Route::delete('notes_perma_del/{id}', ['uses' => 'Admin\NotesController@perma_del', 'as' => 'notes.perma_del']);

    Route::model('messenger', 'App\MessengerTopic');
    Route::get('messenger/inbox', 'Admin\MessengerController@inbox')->name('messenger.inbox');
    Route::get('messenger/outbox', 'Admin\MessengerController@outbox')->name('messenger.outbox');
    Route::resource('messenger', 'Admin\MessengerController');

    Route::resource('tenants', 'Admin\TenantsController');
 
});

app/Tour.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\Tour as Authenticatable;

/**
 * Class Role
 *
 * @package App
 * @property string $title
*/
class Tour extends Authenticatable
{   
    public function __construct()
    {
 
    }      
    public function survey()
    {
        return $this->belongsToMany(Survey::class, 'tour_survey');
    }

    public function validateCredentials(Authenticatable $user, array $credentials)
    {
        die('bob');
        dd($user, $credentials, 'validateCredentials');
    }
    
}

app/Http/Controllers/Admin/ToursController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\StoreTenantsRequest;
use App\Notifications\InvitationSend;
use App\Property;
use App\Http\Controllers\Controller;
use App\User;
use App\Tour;
use App\Vendor;
use Illuminate\Http\Request;

class ToursController extends Controller
{

    /**
     * Display a listing of Tenants.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating new Tenant.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $properties = Property::where('user_id', auth()->user()->id)->pluck('name', 'id');

        return view('admin.tenants.create', compact('properties'));
    }

    /**
     * Store a newly created Tenant in storage.
     *
     * @param  \App\Http\Requests\StoreTenantsRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTenantsRequest $request)
    {
        $user = User::create([
            'name'             => $request->name,
            'email'            => $request->email,
            'password'         => str_random(8),
            'property_id'      => $request->property_id,
            'invitation_token' => substr(md5(rand(0, 9) . $request->email . time()), 0, 32),
        ]);

        $user->role()->attach(3);

        $user->notify(new InvitationSend());

        return redirect()->route('admin.tenants.index');
    }


    /**
     * Remove Property from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $property = Property::findOrFail($id);
        $property->delete();

        return redirect()->route('admin.properties.index');
    }

    public function tourListing(Request $request)
	{
        $user = auth()->user();
        
        $role = $user->role()->first();
        $roleid = $role->id;
        if($roleid == 3){
            $uid = auth()->user()->id;
            $user = User::findOrFail($uid);
            $tours = array();
            $assignedVendors = [0];
            
            $vendors = $user->vendor()->pluck('vendor_id');
            foreach($vendors as $vendorsval){
                $vendor = Vendor::findOrFail($vendorsval);
                $assignedVendors[] = $vendor->vendor_code;
            }
            //echo '<pre>'; print_r($assignedVendors); die;
            $tours = Tour::whereIn('master_vendor', $assignedVendors)
                    ->orWhereIn('sub_vendor', $assignedVendors)
                    ->get();
        }else{
            $tours= Tour::all();

        }
		return view('admin.tour.index',['tours'=>$tours]);
	}

}

resources/views/admin/tour/create.blade.php
@extends('layouts.app')

@section('content')
<div class="page-body">
<div class="row">
    <div class="col-sm-12">
        <!-- Basic Form Inputs card start -->
        <div class="card">
            <div class="card-header">
                <h5>Create user</h5>
                </div>
                <div class="card-block">
            {!! Form::open(['method' => 'POST', 'route' => ['admin.users.store']]) !!}


                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label"> {!! Form::label('name',
                                    trans('global.users.fields.name').'*', ['class' => 'control-label'])
                                    !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '',
                                    'required'
                                    => ''])
                                    !!}
                                </div>
                                <p class="help-block"></p>
                                @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                                @endif
                            </div>
                            <div class="form-group row">

                                <label class="col-sm-2 col-form-label"> {!! Form::label('email',
                                    trans('global.users.fields.email').'*', ['class' =>
                                    'control-label'])
                                    !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' =>
                                    '',
                                    'required' =>
                                    '']) !!}
                                </div>
                                <p class="help-block"></p>
                                @if($errors->has('email'))
                                <p class="help-block">
                                    {{ $errors->first('email') }}
                                </p>
                                @endif

                            </div>
                            <div class="form-group row">

                                <label class="col-sm-2 col-form-label"> {!! Form::label('password',
                                    trans('global.users.fields.password').'*', ['class' =>
                                    'control-label']) !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::password('password', ['class' => 'form-control', 'placeholder' => '',
                                    'required'
                                    =>
                                    '']) !!}
                                </div>
                                <p class="help-block"></p>
                                @if($errors->has('password'))
                                <p class="help-block">
                                    {{ $errors->first('password') }}
                                </p>
                                @endif

                            </div>
                            <div class="form-group row">

                                <label class="col-sm-2 col-form-label"> {!! Form::label('role',
                                    trans('global.users.fields.role').'*', ['class' => 'control-label'])
                                    !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::select('role[]', $roles, old('role'), ['class' => 'form-control select2',
                                    'multiple'
                                    =>
                                    'multiple', 'required' => '']) !!}
                                </div>
                                <p class="help-block"></p>
                                @if($errors->has('role'))
                                <p class="help-block">
                                    {{ $errors->first('role') }}
                                </p>
                                @endif
                            </div>

          

            {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </div>
    </div>
</div>
</div>
</div>
@stop

resources/views/admin/tour/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="page-body">
<div class="row">
    <div class="col-sm-12">
        <!-- Basic Form Inputs card start -->
        <div class="card">
            <div class="card-header">
                <h5>Edit User</h5>
                </div>
                <div class="card-block">
                {!! Form::model($user, ['method' => 'PUT', 'route' => ['admin.users.update', $user->id]]) !!}
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">{!! Form::label('name',
                                    trans('global.users.fields.name').'*',
                                    ['class' => 'control-label']) !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '',
                                    'required'
                                    => ''])
                                    !!}
                                </div>
                                <p class="help-block"></p>
                                @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                                @endif
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">{!! Form::label('email',
                                    trans('global.users.fields.email').'*', ['class' =>
                                    'control-label'])
                                    !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' =>
                                    '',
                                    'required' =>
                                    '']) !!}
                                </div>
                                <p class="help-block"></p>
                                @if($errors->has('email'))
                                <p class="help-block">
                                    {{ $errors->first('email') }}
                                </p>
                                @endif
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">{!! Form::label('password',
                                    trans('global.users.fields.password').'*', ['class' =>
                                    'control-label']) !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::password('password', ['class' => 'form-control', 'placeholder' => '']) !!}
                                </div>
                                <p class="help-block"></p>
                                @if($errors->has('password'))
                                <p class="help-block">
                                    {{ $errors->first('password') }}
                                </p>
                                @endif
                            </div>

                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label"> {!! Form::label('role',
                                    trans('global.users.fields.role').'*', ['class' => 'control-label'])
                                    !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::select('role[]', $roles, old('role') ? old('role') :
                                    $user->role->pluck('id')->toArray(),
                                    ['class' => 'form-control select2', 'multiple' => 'multiple', 'required' => '']) !!}
                                </div>
                                <p class="help-block"></p>
                                @if($errors->has('role'))
                                <p class="help-block">
                                    {{ $errors->first('role') }}
                                </p>
                                @endif
                            </div>
                            <?php if($user->role->pluck('title')->toArray()[0] == 'Customer'){ ?>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label"> {!! Form::label('master_vendor',
                                    'Master Vendors'.'*', ['class' => 'control-label'])
                                    !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::select('master_vendors[]', $master_vendors, old('master_vendors') ? old('master_vendors') :
                                   $user->vendor->pluck('id')->toArray(),
                                    ['class' => 'form-control select2', 'multiple' => 'multiple', 'required' => '']) !!}
                                </div>
                           </div> 

                           <div class="form-group row">
                                <label class="col-sm-2 col-form-label"> {!! Form::label('sub_vendor',
                                    'Sub Vendors'.'*', ['class' => 'control-label'])
                                    !!}</label>
                                <div class="col-sm-10">
                                    {!! Form::select('sub_vendors[]', $sub_vendors, old('sub_vendors') ? old('sub_vendors') :
                                    $user->vendor->pluck('id')->toArray(),
                                    ['class' => 'form-control select2', 'multiple' => 'multiple', 'required' => '']) !!}
                                </div>
                           </div> 
                          <?php } ?>

                      
            {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
            </div>
    </div>
</div>
</div>
</div>
@stop

resources/views/admin/tour/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.users.title')</h3>

   <div class="page-body">
    <div class="row">
        <div class="col-sm-12">
      
        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('global.users.fields.name')</th>
                            <td field-key='name'>{{ $user->name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.users.fields.email')</th>
                            <td field-key='email'>{{ $user->email }}</td>
                        </tr>
                        <!--<tr>
                            <th>@lang('global.users.fields.role')</th>
                            <td field-key='role'>
                                @foreach ($user->role as $singleRole)
                                    <span class="label label-info label-many">{{ $singleRole->title }}</span>
                                @endforeach
                            </td>
                        </tr>-->
                    </table>
                </div>
            </div><!-- Nav tabs -->

<!-- Tab panes -->
<div class="card" style="width:100%">
					<div class="col-sm-12">
					<div class="panel-heading">
					  
					</div>
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="notes">
<table class="table table-bordered table-striped {{ count($notes) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('global.notes.fields.property')</th>
                        <th>@lang('global.notes.fields.user')</th>
                        <th>@lang('global.notes.fields.note-text')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
        </tr>
    </thead>

    <tbody>
        @if (count($notes) > 0)
            @foreach ($notes as $note)
                <tr data-entry-id="{{ $note->id }}">
                    <td field-key='property'>{{ $note->property->name or '' }}</td>
                                <td field-key='user'>{{ $note->user->name or '' }}</td>
                                <td field-key='note_text'>{!! $note->note_text !!}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['notes.restore', $note->id])) !!}
                                    {!! Form::submit(trans('global.app_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['notes.perma_del', $note->id])) !!}
                                    {!! Form::submit(trans('global.app_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                                                </td>
                                @else
                                <td>
                                    @can('view')
                                    <a href="{{ route('notes.show',[$note->id]) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                    @endcan
                                    @can('edit')
                                    <a href="{{ route('notes.edit',[$note->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    @endcan
                                    @can('delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['notes.destroy', $note->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="8">@lang('global.app_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
<div role="tabpanel" class="tab-pane " id="documents">
<table class="table table-bordered table-striped {{ count($documents) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('global.documents.fields.property')</th>
                        <th>@lang('global.documents.fields.user')</th>
                        <th>@lang('global.documents.fields.document')</th>
                        <th>@lang('global.documents.fields.name')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
        </tr>
    </thead>

    <tbody>
        @if (count($documents) > 0)
            @foreach ($documents as $document)
                <tr data-entry-id="{{ $document->id }}">
                    <td field-key='property'>{{ $document->property->name or '' }}</td>
                                <td field-key='user'>{{ $document->user->name or '' }}</td>
                                <td field-key='document'>@if($document->document)<a href="{{ asset(env('UPLOAD_PATH').'/' . $document->document) }}" target="_blank">Download file</a>@endif</td>
                                <td field-key='name'>{{ $document->name }}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['documents.restore', $document->id])) !!}
                                    {!! Form::submit(trans('global.app_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['documents.perma_del', $document->id])) !!}
                                    {!! Form::submit(trans('global.app_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                                                </td>
                                @else
                                <td>
                                    @can('view')
                                    <a href="{{ route('documents.show',[$document->id]) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                    @endcan
                                    @can('edit')
                                    <a href="{{ route('documents.edit',[$document->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    @endcan
                                    @can('delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['documents.destroy', $document->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="9">@lang('global.app_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>


            <p>&nbsp;</p>

            <a href="{{ route('admin.users.index') }}" class="btn btn-secondary">@lang('global.app_back_to_list')</a>
			<p>&nbsp;</p>
            </div>
</div>
</div>
        </div>
    </div>
	  </div>
    </div>
@stop